title: Ayorinde Amao
logo: dataanalysis.jpg
description: I am a data enthusiast with a strong background in data analysis, visualization, and business intelligence. I specialize in transforming raw datasets into clear, actionable insights using tools like Excel (advanced functions, pivot tables, dashboards), Power BI, and SQL. My work focuses on creating dynamic, interactive dashboards that support strategic decision-making across industries, including retail, hospitality, and public health. Passionate about continuous learning, I am currently expanding my technical skills into data engineering and advanced analytics.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
